name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
        with:
            ## limits ssh access and adds the ssh public key for the user which triggered the workflow
            limit-access-to-actor: true
            ## limits ssh access and adds the ssh public keys of the listed GitHub users
            limit-access-to-users: ZhymabekRoman
